# Generated by Django 5.0 on 2023-12-30 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_contacts_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='message',
        ),
    ]
