# Generated by Django 5.0 on 2023-12-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0018_remove_team_descriptions1_remove_team_descriptions2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='image1',
            field=models.ImageField(default=1, upload_to='image1/', verbose_name='Фотографии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condition',
            name='image2',
            field=models.ImageField(default=1, upload_to='image2/', verbose_name='Фотографии'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ConditionInlineInfo',
        ),
    ]
