# Generated by Django 5.0 on 2023-12-30 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
    ]
