# Generated by Django 5.0 on 2023-12-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_blog_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='SettingsPhone',
        ),
    ]
