# Generated by Django 5.0 on 2023-12-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.CharField(max_length=100, verbose_name='Чат ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='id_user',
            field=models.CharField(max_length=100, verbose_name='ID пользователя telegram'),
        ),
    ]
